#!/bin/sh

#
# Run the hook command.
# Note: this will be replaced by the real command during copy.
#
GIT_USER=$(git config user.name)
GIT_EMAIL=$(git config user.email)
COMMIT_MSG_FILE=$1

# Fetch the GIT diff and format it as command input:
DIFF=$(git -c diff.mnemonicprefix=false --no-pager diff -r -p -m -M --full-index --no-color --staged | cat)

# Run GrumPHP
HOOK_COMMAND=$(echo "$(HOOK_COMMAND)" | sed "s/'//g")
(cd "${HOOK_EXEC_PATH}" && echo "${DIFF}" | fin exec ${HOOK_COMMAND} --ansi --skip-success-output)

# Validate exit code of above command
RC=$?
if [[ "${RC}" != 0 ]]; then
  exit ${RC};
fi

# Clean exit
exit 0;
